name: Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
      - run: npm run release
      - name: Publish to npm
        run: npm run publish:changesets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
